name: client
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  animated_splash_screen: ^1.3.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  freezed_annotation: ^2.0.0
  go_router: ^14.6.0
  json_annotation: ^4.8.0
  lottie: ^3.1.3

dev_dependencies:
  build_runner: ^2.3.0
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.0
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/loading.json

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/icon.png"
